export const builders = [
  {
    id: 'b1',
    name: 'Ayesha Khan',
    username: 'ayeshabuilds',
    score: 842,
    momentum: '+18% in 7d',
    streak: '21-day streak',
    focus: 'AI Workflow Systems',
    location: 'Lahore',
    avatar: 'https://ui-avatars.com/api/?name=Ayesha+Khan&background=F97316&color=fff',
    consistency: 88,
    execution: 84,
    engagement: 79,
    outcomes: 70,
    socialProof: 65,
  },
  {
    id: 'b2',
    name: 'Rohan Mehta',
    username: 'rohanexec',
    score: 806,
    momentum: '+14% in 7d',
    streak: '17-day streak',
    focus: 'Developer Infrastructure',
    location: 'Bangalore',
    avatar: 'https://ui-avatars.com/api/?name=Rohan+Mehta&background=EA580C&color=fff',
    consistency: 81,
    execution: 86,
    engagement: 71,
    outcomes: 68,
    socialProof: 60,
  },
  {
    id: 'b3',
    name: 'Mina Park',
    username: 'minaforward',
    score: 773,
    momentum: '+12% in 7d',
    streak: '28-day streak',
    focus: 'B2B SaaS Automation',
    location: 'Seoul',
    avatar: 'https://ui-avatars.com/api/?name=Mina+Park&background=C2410C&color=fff',
    consistency: 79,
    execution: 80,
    engagement: 74,
    outcomes: 64,
    socialProof: 58,
  },
];

export const updates = [
  {
    id: 'u1',
    builderUsername: 'ayeshabuilds',
    product: 'FlowPilot',
    type: 'shipped feature',
    content: 'Released auto-tagging for workflow errors and cut setup time by 22%.',
    time: '2h ago',
    stage: 'BETA -> GROWTH',
  },
  {
    id: 'u2',
    builderUsername: 'rohanexec',
    product: 'Dockit Core',
    type: 'milestone reached',
    content: 'Crossed 100 weekly active teams and opened self-serve onboarding.',
    time: '5h ago',
    stage: 'MVP -> BETA',
  },
  {
    id: 'u3',
    builderUsername: 'minaforward',
    product: 'PulseDesk',
    type: 'lesson learned',
    content: 'Shared learnings on reducing churn from weekly setup review calls.',
    time: '1d ago',
    stage: 'BETA',
  },
];

export const opportunities = [
  {
    id: 'o1',
    type: 'Hiring Match',
    builderUsername: 'ayeshabuilds',
    fitScore: 92,
    status: 'pending',
    detail: 'Staff Engineer role at a workflow automation startup.',
  },
  {
    id: 'o2',
    type: 'Collaboration Match',
    builderUsername: 'rohanexec',
    fitScore: 88,
    status: 'active',
    detail: 'Co-build API reliability toolkit with a backend observability team.',
  },
  {
    id: 'o3',
    type: 'Funding Interest',
    builderUsername: 'minaforward',
    fitScore: 84,
    status: 'new',
    detail: 'Early-stage investor requested a product execution timeline.',
  },
];

export const lifecycleTimeline = [
  { stage: 'IDEA', date: 'Jan 12, 2026' },
  { stage: 'MVP', date: 'Feb 03, 2026' },
  { stage: 'BETA', date: 'Mar 18, 2026' },
  { stage: 'GROWTH', date: 'Apr 14, 2026' },
];
